package com.mycompany.calculadora.visao;
import com.mycompany.calculadora.controle.CalculadoraControle;
import com.mycompany.calculadora.enums.EnumOperacao;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;


public class Tela extends javax.swing.JFrame {

    private CalculadoraControle calculadoraControle;
    
    private EnumOperacao ultimaOperacao;
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        calculadoraControle = new CalculadoraControle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtAC = new javax.swing.JButton();
        BtMaisMenos = new javax.swing.JButton();
        BtPorcento = new javax.swing.JButton();
        BtDiv = new javax.swing.JButton();
        Bt7 = new javax.swing.JButton();
        Bt8 = new javax.swing.JButton();
        Bt9 = new javax.swing.JButton();
        BtVezes = new javax.swing.JButton();
        Bt4 = new javax.swing.JButton();
        Bt5 = new javax.swing.JButton();
        Bt6 = new javax.swing.JButton();
        BtMenos = new javax.swing.JButton();
        Bt1 = new javax.swing.JButton();
        Bt2 = new javax.swing.JButton();
        Bt3 = new javax.swing.JButton();
        BtMais = new javax.swing.JButton();
        BtZero = new javax.swing.JButton();
        BtVirg = new javax.swing.JButton();
        BtIgual = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        Valor.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        Valor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Valor.setText("0,00");
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        BtAC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtAC.setText("AC");
        BtAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtACActionPerformed(evt);
            }
        });
        jPanel1.add(BtAC);

        BtMaisMenos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtMaisMenos.setText("+/-");
        BtMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMaisMenosActionPerformed(evt);
            }
        });
        jPanel1.add(BtMaisMenos);

        BtPorcento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtPorcento.setText("%");
        jPanel1.add(BtPorcento);

        BtDiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtDiv.setText("/");
        BtDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDivActionPerformed(evt);
            }
        });
        jPanel1.add(BtDiv);

        Bt7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt7.setText("7");
        Bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt7);

        Bt8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt8.setText("8");
        Bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt8);

        Bt9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt9.setText("9");
        Bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt9);

        BtVezes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtVezes.setText("*");
        BtVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVezesActionPerformed(evt);
            }
        });
        jPanel1.add(BtVezes);

        Bt4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt4.setText("4");
        Bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt4);

        Bt5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt5.setText("5");
        Bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt5);

        Bt6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt6.setText("6");
        Bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt6);

        BtMenos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtMenos.setText("-");
        BtMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMenosActionPerformed(evt);
            }
        });
        jPanel1.add(BtMenos);

        Bt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt1.setText("1");
        Bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt1);

        Bt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt2.setText("2");
        Bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt2);

        Bt3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bt3.setText("3");
        Bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(Bt3);

        BtMais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtMais.setText("+");
        BtMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMaisActionPerformed(evt);
            }
        });
        jPanel1.add(BtMais);

        BtZero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtZero.setText("0");
        BtZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtZeroActionPerformed(evt);
            }
        });
        jPanel1.add(BtZero);

        BtVirg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtVirg.setText(",");
        BtVirg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVirgActionPerformed(evt);
            }
        });
        jPanel1.add(BtVirg);

        BtIgual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtIgual.setText("=");
        BtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIgualActionPerformed(evt);
            }
        });
        jPanel1.add(BtIgual);

        BtFechar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtFechar.setText("Fechar");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        jPanel1.add(BtFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addComponent(Valor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorActionPerformed
    private void BtMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMaisMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtMaisMenosActionPerformed
    private void Bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt7ActionPerformed
        digitaNumero("7");
    }//GEN-LAST:event_Bt7ActionPerformed
    private void Bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt8ActionPerformed
        digitaNumero("8");
    }//GEN-LAST:event_Bt8ActionPerformed
    private void Bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt9ActionPerformed
        digitaNumero("9");
    }//GEN-LAST:event_Bt9ActionPerformed
    private void Bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt4ActionPerformed
        digitaNumero("4");
    }//GEN-LAST:event_Bt4ActionPerformed
    private void Bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt5ActionPerformed
        digitaNumero("5");
    }//GEN-LAST:event_Bt5ActionPerformed
    private void Bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt6ActionPerformed
        digitaNumero("6");
    }//GEN-LAST:event_Bt6ActionPerformed
    private void Bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt1ActionPerformed
        digitaNumero("1");
    }//GEN-LAST:event_Bt1ActionPerformed
    private void Bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt2ActionPerformed
        digitaNumero("2");
    }//GEN-LAST:event_Bt2ActionPerformed
    private void Bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt3ActionPerformed
        digitaNumero("3");
    }//GEN-LAST:event_Bt3ActionPerformed
    private void BtZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtZeroActionPerformed
        digitaNumero("0");
    }//GEN-LAST:event_BtZeroActionPerformed

    private void BtVirgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVirgActionPerformed
        digitaNumero(",");
    }//GEN-LAST:event_BtVirgActionPerformed
    private void BtMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMaisActionPerformed
        calculadoraControle.realizaOperacao(EnumOperacao.SOMA, stringToDouble(Valor.getText()));
        ultimaOperacao = EnumOperacao.SOMA;
        limpa();
    }//GEN-LAST:event_BtMaisActionPerformed
    private Double stringToDouble(String numero) {
        NumberFormat nf = NumberFormat.getInstance();
        Double dv = null;
        try {
            dv = nf.parse(numero).doubleValue();
        } catch (ParseException ex) {
            
        }
        return dv;
    }
    private void BtMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMenosActionPerformed
        calculadoraControle.realizaOperacao(EnumOperacao.SUBTRACAO, stringToDouble(Valor.getText()));
        ultimaOperacao = EnumOperacao.SUBTRACAO;
        limpa();
    }//GEN-LAST:event_BtMenosActionPerformed

    private void BtACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtACActionPerformed
        limpa();
        calculadoraControle.zerar();
    }//GEN-LAST:event_BtACActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDivActionPerformed
        calculadoraControle.realizaOperacao(EnumOperacao.DIVISAO, stringToDouble(Valor.getText()));
        ultimaOperacao = EnumOperacao.DIVISAO;    
        limpa();        
    }//GEN-LAST:event_BtDivActionPerformed

    private void BtVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVezesActionPerformed
        ultimaOperacao = EnumOperacao.MULTIPLICACAO;
        limpa();
    }//GEN-LAST:event_BtVezesActionPerformed

    private void BtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIgualActionPerformed
     
    }//GEN-LAST:event_BtIgualActionPerformed
    private String DoubleToString(String numero) {
        if (numero != null) {
            DecimalFormat formato = new DecimalFormat("##,###,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
            
        }
        return "";
    }

    private void limpa(){
        Valor.setText("0,00");
    }
    
    private void digitaNumero(String caractere) {
        if (Valor.getText().equals("0,00")) {
            Valor.setText(caractere);
        } else {
            if (caractere.equals(",") && Valor.getText().contains(",")) {    
            
            }else {
                Valor.setText(Valor.getText().concat(caractere));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt1;
    private javax.swing.JButton Bt2;
    private javax.swing.JButton Bt3;
    private javax.swing.JButton Bt4;
    private javax.swing.JButton Bt5;
    private javax.swing.JButton Bt6;
    private javax.swing.JButton Bt7;
    private javax.swing.JButton Bt8;
    private javax.swing.JButton Bt9;
    private javax.swing.JButton BtAC;
    private javax.swing.JButton BtDiv;
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtIgual;
    private javax.swing.JButton BtMais;
    private javax.swing.JButton BtMaisMenos;
    private javax.swing.JButton BtMenos;
    private javax.swing.JButton BtPorcento;
    private javax.swing.JButton BtVezes;
    private javax.swing.JButton BtVirg;
    private javax.swing.JButton BtZero;
    private javax.swing.JTextField Valor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
